name: app-ci-workflow

run-name: Workflow triggered by @${{ github.actor }}

on: [push, pull_request]

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build `app` test image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          tags: app:test
          outputs: type=docker,dest=/tmp/apptest.tar

      - name: Store `app` test image for later stage(s)
        uses: actions/upload-artifact@v3
        with:
          name: apptest
          path: /tmp/apptest.tar
  
  run-unit-tests:
    runs-on: ubuntu-latest
    needs: build-images

    steps:
      - name: Fetch `app` test image
        uses: actions/download-artifact@v3
        with:
          name: apptest
          path: /tmp

      - name: Load `app` test image
        run: |
          docker load --input /tmp/apptest.tar

      - name: Run `app` unit tests
        run: |
          docker run app:test python -m pytest tests/
